wandb:
  project: nbody_to_hydro
  entity: symmetry_group
  mode: online

training:
  lr: 1e-3
  epochs: 300
  val_every: 10
  checkpoint: True
  debug: False
  clip_grad_norm: 1

model:
  model: egnn
  width: 64
  n_layers: 4
  use_extra_feats: False

dataset:
  path: '/network/scratch/t/tara.akhoundsadegh/camels_data/'
  suite: 'SIMBA'
  sim_set: 'CV'
  threshold: 0.16
  frac_val: 0.2
  frac_test: 0
  load: false
